#!/bin/sh
# ./node_modules/.bin/webpack-dev-server \
#   --devtool inline-source-map \
#   --inline \
#   --colors \
#   --progress \
#   --display-error-details \
#   --display-reasons &
npm start
kill %1
kill %2